# Generated by Django 3.2.15 on 2022-08-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='apporoved_comment',
            new_name='approved_comment',
        ),
    ]
